apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
  type: {{ .Values.service.type }}

